name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

  workflow_dispatch:

env:
  python-version: "3.11"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        tox-env: ["py37", "py38", "py39", "py310", "py311"]

    steps:
      - uses: actions/checkout@v3

      - name: Cache conda packages
        uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ matrix.tox-env }}-${{ hashFiles('ci/requirements-*.yml') }}

      - name: Install base Conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ env.python-version }}
          channels: conda-forge

      - name: Install tox
        shell: bash -l {0}
        run: |
          conda install -c conda-forge tox

      - name: Run tests
        shell: bash -l {0}
        run: |
          tox -vve "${{ matrix.tox-env }}"
